import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import { useCursorContext } from "../hooks/useCursorContext";

export default function Home() {
  const { setter } = useCursorContext();

  return (
    <motion.div className={styles.parent} exit={{ x: -200 }}>
      <Head>
        <title>Ram&apos;s neck of the woods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="/fonts/GTWalsheim/GTWalsheimPro-Medium.woff2"
          rel="preload"
          as="font"
        />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <nav>
            <ul>
              <motion.li
                className={styles.notesLink}
                whileHover={{ scale: 1.2 }}
                whileTap={{ scale: 0.9 }}
                onMouseEnter={() => {
                  setter({ type: "hidden" });
                }}
                onMouseLeave={() => {
                  setter({ type: "solid" });
                }}
              >
                <Link href="/notes">Musings → </Link>
              </motion.li>
            </ul>
          </nav>
        </header>

        <main className={styles.main}>
          <motion.h1
            className={styles.title}
            onMouseEnter={() =>
              setter({
                type: "hollowPurple",
              })
            }
            onMouseLeave={() => {
              setter({ type: "solid" });
            }}
          >
            Ramanujan Veeravalli
          </motion.h1>

          <p
            className={styles.description}
            onMouseEnter={() =>
              setter({
                type: "hollowWhite",
              })
            }
            onMouseLeave={() => {
              setter({ type: "solid" });
            }}
          >
            Software Engineer{" "}
            <a
              target="_blank"
              href="https://www.paypal.com"
              rel="noreferrer"
              onMouseEnter={() =>
                setter({
                  type: "hollowBlue",
                })
              }
              onMouseLeave={() => {
                setter({ type: "solid" });
              }}
            >
              @ PayPal
            </a>
          </p>

          <div className={styles.grid}></div>
        </main>
      </div>
    </motion.div>
  );
}
